### ISSUE TITLE
Possibility to devendor dependencies

### ISSUE THREAD

**Issue by awvwgk** [qcserenity/serenity#9]
For the spack package I had to devendor all dependencies which are automatically downloaded by serenity's build system. I would be happy to contribute a patch based on

https://github.com/spack/spack/blob/bab7694724cc236ea13f87a467ec739a9b7a56f8/var/spack/repos/builtin/packages/serenity/package.py#L38-L110

**Comment by nabbelbabbel** [comment]
If I understand the files behind the link correctly, this now forces the user to install all dependencies?

I am fine with this being an option, but would want to keep the automatic downloads. I would think that a cmake option switching between the two behaviors would be reasonable.

The automatic install was made so that there is a more simple install that ensures correct versions of all dependencies are installed.
(Without a 3rd party package manager.)
Many of the downloaded packages did not have cmake files that allowed for version checks.
(This may have improved in the meantime, but #7 may hint that version controll is still required.)

**Comment by awvwgk** [comment]
> If I understand the files behind the link correctly, this now forces the user to install all dependencies?

For the purpose of developing the spack package I turned downloading dependencies into a hard error. For upstreaming this patch to serenity retaining the option to download would be wanted, of course.

**Comment by nabbelbabbel** [comment]
I would be happy to add this option, if you already have a patch for something like this even better.

**Comment by awvwgk** [comment]
Sure, I can open a PR, just wanted to make sure that contributions are wanted. My experience with contributing to release-only repos has been quite mixed so far.

**Comment by nabbelbabbel** [comment]
FYI I will subsume your changes into the next release. This should be within a few weeks.

**Comment by nabbelbabbel** [comment]
Staged for 1.5.0

**Comment by nabbelbabbel** [comment]
This issue has been addressed in Serenity v1.5.0 .
Thanks for the feedback.
